import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const reportsTable = pgTable("reports", {
  // Random UUID generated by the API route — doubles as the share slug
  id: text("id").primaryKey(),
  type: text("type").notNull(), // 'business' | 'individual' | 'job-description'
  industry: text("industry"),
  website: text("website"),
  description: text("description"),
  reportHtml: text("report_html").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertReportSchema = createInsertSchema(reportsTable).omit({ id: true, createdAt: true });
export type InsertReport = z.infer<typeof insertReportSchema>;
export type Report = typeof reportsTable.$inferSelect;
